export const BOSS_ITEMS = [
  'Bibit Micin',
  'Bibit Kecubung',
  'Security A',
  'Red Laptop',
  'Thermite',
  'Security B',
  'Blue Laptop',
  'Advance Lockpick',
  'Security D',
  'Green Laptop',
  'Trojan USB',
  'Micro SMG',
  'Heavy Sniper',
  'Desert Eagle',
  'Double Action Revolver',
  'AK 47',
  'Mini SMG',
  'Revolver MK2',
  '9mm',
  '50 AE',
  '7.62 x 39',
  '45 ACP',
  '44 Magnum',
  '50 BMG',
  'Heavy Armor',
  'Bom Pipa',
  'Uang Merah',
  'Uang Hitam',
  'RPG',
  'Pistol .50'
] as const;

export type BossItemType = typeof BOSS_ITEMS[number];